from paddleocr import PPStructureV3
from pathlib import Path
import os
import paddle

# (懒加载部分的代码是正确的，无需改动)
DEVICE_STR = 'gpu' if paddle.is_compiled_with_cuda() else 'cpu'
PIPELINE_ENGINE = None

def get_engine():
    global PIPELINE_ENGINE
    if PIPELINE_ENGINE is None:
        try:
            PIPELINE_ENGINE = PPStructureV3(use_doc_orientation_classify=False,
                                            use_doc_unwarping=False,
                                            device=DEVICE_STR)
        except Exception as e:
            raise e
    return PIPELINE_ENGINE

def process_file(input_file_path, dedicated_output_dir):
    """
    一个统一的处理函数，它会先完成自己的任务，然后清理掉库产生的垃圾文件。
    """
    try:
        engine = get_engine()
        if engine is None:
            raise RuntimeError("OCR Engine could not be initialized.")

        print(f"Processing file with cleanup logic: {input_file_path}")
        output_path = Path(dedicated_output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # --- 【核心修改：增加清理逻辑】 ---

        # 1. 执行 predict，允许它产生任何副作用（即那些UUID命名的md文件）
        output = engine.predict(input=input_file_path)

        if not output:
            return False

        # 2. 像之前一样，我们只收集数据，用于生成我们自己的、命名正确的文件
        markdown_list = []
        markdown_images = []
        for page_res in output:
            md_info = page_res.markdown 
            markdown_list.append(md_info)
            images = md_info.get("markdown_images", {})
            if images:
                markdown_images.append(images)
        
        final_markdown_text = engine.concatenate_markdown_pages(markdown_list)
        
        # 3. 生成我们唯一想要的、命名正确的 Markdown 文件
        original_stem = Path(dedicated_output_dir).name
        correct_md_filename = f"{original_stem}.md"
        correct_md_filepath = output_path / correct_md_filename
        with open(correct_md_filepath, "w", encoding="utf-8") as f:
            f.write(final_markdown_text)
        
        # 4. 保存所有图片（这部分逻辑是正确的）
        for item in markdown_images:
            for path, image_data in item.items():
                full_image_path = output_path / path
                full_image_path.parent.mkdir(parents=True, exist_ok=True)
                image_data.save(full_image_path)

        # 5. 【清道夫逻辑】开始清理！
        print(f"Cleaning up extraneous files generated by the library...")
        files_to_delete = []
        for filename in os.listdir(output_path):
            # 找出所有以 .md 结尾，但名字不是我们想要的那个正确名字的文件
            if filename.endswith(".md") and filename != correct_md_filename:
                files_to_delete.append(filename)
        
        for f in files_to_delete:
            file_path_to_delete = output_path / f
            print(f"Deleting junk file: {file_path_to_delete}")
            os.remove(file_path_to_delete)
        
        print(f"Cleanup complete. {len(files_to_delete)} junk file(s) removed.")
        # --- 修改结束 ---

        print(f"Successfully processed. Final results are in '{dedicated_output_dir}'")
        return True

    except Exception as e:
        print(f"Error during file processing: {e}")
        import traceback
        traceback.print_exc()
        return False
