from paddleocr import PPStructureV3
from pathlib import Path
import os
import paddle

# (懒加载部分的代码是正确的，无需改动)
DEVICE_STR = 'gpu' if paddle.is_compiled_with_cuda() else 'cpu'
PIPELINE_ENGINE = None

def get_engine():
    global PIPELINE_ENGINE
    if PIPELINE_ENGINE is None:
        try:
            PIPELINE_ENGINE = PPStructureV3(use_doc_orientation_classify=False,
                                            use_doc_unwarping=False,
                                            device=DEVICE_STR)
        except Exception as e:
            raise e
    return PIPELINE_ENGINE

def process_file(input_file_path, dedicated_output_dir):
    """
    一个统一的处理函数，它会先完成自己的任务，然后清理掉库产生的垃圾文件。
    """
    try:
        engine = get_engine()
        if engine is None:
            raise RuntimeError("OCR Engine could not be initialized.")

        print(f"Processing file with cleanup logic: {input_file_path}")
        output_path = Path(dedicated_output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        

        output = engine.predict(input=input_file_path)

        if not output:
            return False

        markdown_list = []
        markdown_images = []
        for page_res in output:
            md_info = page_res.markdown 
            markdown_list.append(md_info)
            images = md_info.get("markdown_images", {})
            if images:
                markdown_images.append(images)
        
        final_markdown_text = engine.concatenate_markdown_pages(markdown_list)
        
        original_stem = Path(dedicated_output_dir).name
        correct_md_filename = f"{original_stem}.md"
        correct_md_filepath = output_path / correct_md_filename
        with open(correct_md_filepath, "w", encoding="utf-8") as f:
            f.write(final_markdown_text)
        
        for item in markdown_images:
            for path, image_data in item.items():
                corrected_path = Path("imgs") / Path(path).name
                full_image_path = output_path / corrected_path
                full_image_path.parent.mkdir(parents=True, exist_ok=True)
                image_data.save(full_image_path)

        print(f"Cleaning up extraneous files generated by the library...")
        files_to_delete = []
        for filename in os.listdir(output_path):
            if filename.endswith(".md") and filename != correct_md_filename:
                files_to_delete.append(filename)
        
        for f in files_to_delete:
            file_path_to_delete = output_path / f
            print(f"Deleting junk file: {file_path_to_delete}")
            os.remove(file_path_to_delete)
        print(f"Cleanup complete. {len(files_to_delete)} junk file(s) removed.")
        print(f"Successfully processed. Final results are in '{dedicated_output_dir}'")
        return True

    except Exception as e:
        print(f"Error during file processing: {e}")
        import traceback
        traceback.print_exc()
        return False
